# Generated by Django 4.2.2 on 2024-01-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_merchant_id_order_payment_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
